[project]
name = "deps"
version = "0.0.0"

[lib]
name = "null"

[dependencies]
libc = "0.1"
getopts = "0.2"
bit-vec = "0.4"
bit-set = "0.2"
vec_map = "0.3"
num_cpus = "0.2"
rand = "0.3"
regex = "0.1"
rust-crypto = "0.2"
rustc-serialize = "0.3"
time = "0.1"
unicode-width = "0.1"
winapi = "0.2"
advapi32-sys = "0.1"
kernel32-sys = "0.1"
walker = "^1.0"
filetime = "0.1"
