#!/bin/bash
source environ.sh

BROKEN

GIT=https://github.com/redox-os/llvm.git
GIT_BRANCH=redox
DIR=llvm

MAKE_DIR="build"
CXX_FLAGS="--sysroot=$SYSROOT"
CMAKE_ARGS=(-Wno-dev -DCMAKE_CROSSCOMPILING=True -DCMAKE_INSTALL_PREFIX="$PREFIX"  -DLLVM_TABLEGEN=/usr/bin/llvm-tblgen -DLLVM_DEFAULT_TARGET_TRIPLE=$HOST -DLLVM_TARGET_ARCH=$ARCH -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_SYSTEM_NAME=Generic -DPYTHON_EXECUTABLE=/usr/bin/python2 -DCMAKE_CXX_FLAGS="$CXX_FLAGS" -DUNIX=1 -DLLVM_ENABLE_THREADS=0)
cmake_template $*
