#!/bin/bash
source environ.sh

BROKEN

GIT=https://github.com/redox-os/llvm.git
GIT_BRANCH=redox
DIR=llvm

#export AR=
#export AS=
#export CC=
#export CXX=
#export LD=
#export NM=

MAKE_DIR="build"
#CONFIGURE="../configure"
#CONFIGURE_ARGS="--host=${HOST} --enable-static --disable-shared --disable-dlopen --enable-targets=x86_64 --with-python=/usr/bin/python2"
#CXX_FLAGS="-L$PWD/../artifacts/usr/lib -isystem $PWD/../artifacts/usr/include"
CXX_FLAGS="--sysroot=$SYSROOT"
#CMAKE_ARGS=(-Wno-dev -DCMAKE_CROSSCOMPILING=True -DCMAKE_INSTALL_PREFIX='$PREFIX' -DLLVM_TABLEGEN='$PREFIX'/bin/llvm-tblgen -DLLVM_DEFAULT_TARGET_TRIPLE=$HOST -DLLVM_TARGET_ARCH=$ARCH -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_SYSTEM_NAME=Generic -DPYTHON_EXECUTABLE=/usr/bin/python2 -DUNIX=1 -DCMAKE_CXX_FLAGS="$CXX_FLAGS")
#CMAKE_ARGS=(-Wno-dev -DCMAKE_CROSSCOMPILING=True -DCMAKE_INSTALL_PREFIX="$PREFIX" -DLLVM_TABLEGEN="$PREFIX"/bin/llvm-tblgen -DLLVM_DEFAULT_TARGET_TRIPLE=$HOST -DLLVM_TARGET_ARCH=$ARCH -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_SYSTEM_NAME=Generic -DPYTHON_EXECUTABLE=/usr/bin/python2 -DCMAKE_CXX_FLAGS="$CXX_FLAGS" -DUNIX=1 -DLLVM_ENABLE_THREADS=0)
CMAKE_ARGS=(-Wno-dev -DCMAKE_CROSSCOMPILING=True -DCMAKE_INSTALL_PREFIX="$PREFIX"  -DLLVM_TABLEGEN=/usr/bin/llvm-tblgen -DLLVM_DEFAULT_TARGET_TRIPLE=$HOST -DLLVM_TARGET_ARCH=$ARCH -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_SYSTEM_NAME=Generic -DPYTHON_EXECUTABLE=/usr/bin/python2 -DCMAKE_CXX_FLAGS="$CXX_FLAGS" -DUNIX=1 -DLLVM_ENABLE_THREADS=0)
#CMAKE_ARGS=(-Wno-dev -DCMAKE_CROSSCOMPILING=True -DCMAKE_INSTALL_PREFIX="$PREFIX"  -DLLVM_DEFAULT_TARGET_TRIPLE=$HOST -DLLVM_TARGET_ARCH=$ARCH -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_SYSTEM_NAME=Generic -DPYTHON_EXECUTABLE=/usr/bin/python2 -DCMAKE_CXX_FLAGS="$CXX_FLAGS" -DUNIX=1 -DLLVM_ENABLE_THREADS=0 -DCMAKE_C_COMPILER=$HOST-gcc)
cmake_template $*
